GET http://localhost:5044/games/

###
GET http://localhost:5044/games/61

###
POST http://localhost:5044/games/
Content-Type: application/json

{
  "genre": "Action RPG",
  "price": 59.99,
  "releaseDate": "2020-12-10"
}
